version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ${WEBAPP_STORAGE_HOME}/pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  api:
    image: emmotion/emmotion_api
    container_name: api
    ports:
      - 3030:3030
    environment:
      NODE_PATH: dist
      TYPEORM_HOST: db
      JWT_SECRET: sectet_key_here
      SERVER_HOST: localhost.com
    restart: always
    links:
      - migration
  client:
    image: emmotion/emmotion_client
    container_name: client
    ports:
      - 3000:3000
    restart: always
    links:
      - api
  migration:
    image: emmotion/emmotion_api
    command: yarn migrate
    volumes:
      - ${WEBAPP_STORAGE_HOME}/pg_data:/var/lib/postgresql/data
    environment:
      TYPEORM_HOST: db
    links:
      - db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ${WEBAPP_STORAGE_HOME}/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - client
      - api
    ports:
      - 80:8989